// constants.js
//    Defines constants useful for battleship game
// =============================================================================
//                            DO NOT EDIT THIS FILE
// =============================================================================
//      written by: Sean
// #############################################################################

// battleship board side length
const BOARD_LEN = 6;
// describes image file paths
const EXPLOSION_IMG = './media/explosion.png', SPLASH_IMG = './media/splash.png';